[[shades]]
name = "color-filter"
default = true

# [[shades]]
# name = "color-filter"
# default = false

# [[shades]]
# name = "grayscale"
# default = false

# [[shades]]
# name = "invert-colors"
# default = false

# [[shades]]
# name = "blue-light-filter"
# start_time = 19:00:00
# end_time = 06:00:00
