#!/bin/bash

# Set GTK Theme, Icons, Cursor and Fonts

THEME='Graphite-Dark-compact'
ICONS='Papirus-Dark'
FONT='JetBrainsMono Nerd Font Propo Bold 12'
CURSOR='rose-pine-hyprcursor'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}
apply_themes
